// Mocks generated by Mockito 5.4.6 from annotations
// in manyoyo_app/test/features/sessions/sessions_notifier_test.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i3;

import 'package:cookie_jar/src/cookie_jar.dart' as _i2;
import 'package:mockito/mockito.dart' as _i1;
import 'package:universal_io/io.dart' as _i4;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: must_be_immutable
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class
// ignore_for_file: invalid_use_of_internal_member

/// A class which mocks [CookieJar].
///
/// See the documentation for Mockito's code generation for more information.
class MockCookieJar extends _i1.Mock implements _i2.CookieJar {
  MockCookieJar() {
    _i1.throwOnMissingStub(this);
  }

  @override
  bool get ignoreExpires =>
      (super.noSuchMethod(Invocation.getter(#ignoreExpires), returnValue: false)
          as bool);

  @override
  _i3.Future<void> saveFromResponse(Uri? uri, List<_i4.Cookie>? cookies) =>
      (super.noSuchMethod(
            Invocation.method(#saveFromResponse, [uri, cookies]),
            returnValue: _i3.Future<void>.value(),
            returnValueForMissingStub: _i3.Future<void>.value(),
          )
          as _i3.Future<void>);

  @override
  _i3.Future<List<_i4.Cookie>> loadForRequest(Uri? uri) =>
      (super.noSuchMethod(
            Invocation.method(#loadForRequest, [uri]),
            returnValue: _i3.Future<List<_i4.Cookie>>.value(<_i4.Cookie>[]),
          )
          as _i3.Future<List<_i4.Cookie>>);

  @override
  _i3.Future<void> deleteAll() =>
      (super.noSuchMethod(
            Invocation.method(#deleteAll, []),
            returnValue: _i3.Future<void>.value(),
            returnValueForMissingStub: _i3.Future<void>.value(),
          )
          as _i3.Future<void>);

  @override
  _i3.Future<void> delete(Uri? uri, [bool? withDomainSharedCookie = false]) =>
      (super.noSuchMethod(
            Invocation.method(#delete, [uri, withDomainSharedCookie]),
            returnValue: _i3.Future<void>.value(),
            returnValueForMissingStub: _i3.Future<void>.value(),
          )
          as _i3.Future<void>);
}
